const mongoose = require('mongoose');

const phase1 = new mongoose.Schema({
    discordid: {
        type: String,
        required: true,
        unique: true,
    },
    money: Number,
    energy: Number,
    cooldown: Number,
    coal_ore: Number,
    graphite: Number,
    iron_ore: Number,
    iron_ingot: Number,
    copper_ore: Number,
    copper_ingot: Number,
    silicon_ore: Number,
    high_purity_silicon: Number,
    titanium_ore: Number,
    titanium_ingot: Number,
    gear: Number,
    magnet: Number,
    magnetic_coil: Number,
    motor: Number,
    circuit_board: Number,
    tails_credit_acc_v1: Number,
    microcrystal: Number,
    processor: Number,
    electromagnetic_turbine: Number,
    steel: Number,
    thruster: Number,
    tails_credit_acc_v2: Number,
    transformer_v1: Number,
    mining_acc_v1: Number,
    oil_extractor: Number,
    oil: Number,
    hydrogen_production_tech: Number,
    hydrogen: Number,
    graphene: Number,
    carbon_nanotube: Number,
    titanium_alloy: Number,
    frame_material: Number,
    organic_crystal: Number,
    titanium_crystal: Number,
    super_crystal: Number,
    crystal_filter: Number,
    unipolar_magnet: Number,
    tails_credit_acc_v3: Number,
});

module.exports = mongoose.model('phase1', phase1);
